[package]
name = "data_depth"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.5"
prost = "0.13.5"
prost-build = "0.13.5"
rmp-serde = "1.3.0"
serde = {version="1.0.218", features=["derive"]}
serde_json = "1.0.140"
tokio = "1.43.0"
